import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getFirestore,doc,onSnapshot,setDoc,serverTimestamp,collection,getDocs,query,orderBy,limit} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyCa3ntHg9DqV3JefcvFP9cg8xCmwm0wlLo',authDomain:'facturacion-drink.firebaseapp.com',projectId:'facturacion-drink',storageBucket:'facturacion-drink.firebasestorage.app',messagingSenderId:'1093109447685',appId:'1:1093109447685:web:a3015f3494f757a625b06c'};
const app=initializeApp(firebaseConfig),db=getFirestore(app),deviceId='aire-principal',$=id=>document.getElementById(id),ref=n=>doc(db,'qpAir',deviceId,'sync',n);
let state={power:false,temp:24,mode:3,fan:0,swing:false,turbo:false},reported=null,pending=null,debounce=null,timeout=null,serverReady=false,session=0;
const names={3:'Frío',2:'Seco',7:'Ventilar',8:'Automático'};
function online(){return navigator.onLine&&serverReady&&reported&&Date.now()-(reported.lastSeenMs||0)<90000}
function message(s){$('status').textContent=s}
function render(){
 $('temperature').textContent=state.temp;$('modeLabel').textContent=names[state.mode]||'Modo';$('powerLabel').textContent=state.power?'ENCENDIDO · AJUSTE':'APAGADO · AJUSTE';$('powerText').textContent=state.power?'Apagar aire':'Encender aire';$('power').classList.toggle('on',state.power);document.querySelector('.dial').style.setProperty('--sweep',`${30+(state.temp-16)/14*250}deg`);
 document.querySelectorAll('[data-mode]').forEach(b=>{let a=+b.dataset.mode===state.mode;b.classList.toggle('selected',a);b.setAttribute('aria-pressed',a)});document.querySelectorAll('[data-fan]').forEach(b=>{let a=+b.dataset.fan===state.fan;b.classList.toggle('selected',a);b.setAttribute('aria-pressed',a)});['swing','turbo'].forEach(k=>document.querySelector(`[data-action=${k}]`)?.setAttribute('aria-pressed',state[k]));
 const ok=online();$('connection').textContent=ok?'● Disponible':'Sin conexión';$('connection').classList.toggle('online',!!ok);document.querySelectorAll('#dashboard button[data-action],#dashboard button[data-mode],#dashboard button[data-fan]').forEach(b=>b.disabled=!ok||!!pending);$('lastSeen').textContent=reported?.lastSeenMs?'Última comunicación · '+new Date(reported.lastSeenMs).toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'Sin comunicación todavía';
}
function cancel(){clearTimeout(debounce);clearTimeout(timeout);debounce=null;pending=null}function fail(t){cancel();if(reported?.state)state={...reported.state};message(t);render()}
async function send(){debounce=null;if(!online()||pending){fail('Tarjeta no disponible');return}const id=crypto.randomUUID(),my=session;pending=id;render();message('Enviando ajustes…');timeout=setTimeout(()=>pending===id&&fail('Sin confirmación. Comprueba la tarjeta.'),35000);try{await setDoc(ref('command'),{id,bootId:reported.bootId,baseRevision:reported.revision,createdMs:Date.now(),createdAt:serverTimestamp(),state:{...state}});if(session===my&&pending===id)message('Esperando transmisión IR…')}catch(e){if(session===my&&pending===id)fail(e.code==='permission-denied'?'Acceso denegado. Revisa las reglas.':'No se pudo enviar. Revisa tu conexión.')}}
document.querySelector('#dashboard').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||!online()||pending)return;if(b.dataset.mode)state.mode=+b.dataset.mode;if(b.dataset.fan){state.fan=+b.dataset.fan;state.turbo=false}switch(b.dataset.action){case'minus':state.temp=Math.max(16,state.temp-1);break;case'plus':state.temp=Math.min(30,state.temp+1);break;case'power':state.power=!state.power;break;case'swing':state.swing=!state.swing;state.turbo=false;break;case'turbo':state.turbo=!state.turbo;if(state.turbo){state.fan=5;state.swing=true}break;case'resend':break;default:if(!b.dataset.mode&&!b.dataset.fan)return}render();message('Preparando ajustes…');clearTimeout(debounce);debounce=setTimeout(send,b.dataset.action==='resend'?0:350)});
function connect(){session++;cancel();reported=null;serverReady=false;message('Conectando con la tarjeta…');render();onSnapshot(ref('reported'),{includeMetadataChanges:true},snap=>{serverReady=!snap.metadata.fromCache;if(!snap.exists()){message('Falta vincular o conectar la tarjeta');render();return}const prev=reported;reported=snap.data();if(pending&&reported.ackId===pending){cancel();message('Señal IR transmitida')}else if(pending&&prev&&(reported.bootId!==prev.bootId||reported.revision!==prev.revision)){fail('El estado cambió en la tarjeta. Vuelve a intentarlo.')}else if(!pending&&!debounce)message('Ajustes sincronizados');if(!pending&&!debounce&&reported.state)state={...reported.state};render()},()=>{serverReady=false;fail('No se pudo leer el estado. Revisa Firestore.')})}
const fs=$('fullscreen');
function fsEl(){return document.fullscreenElement||document.webkitFullscreenElement||null}
function syncFS(){const a=!!fsEl();fs.classList.toggle('active',a);fs.title=a?'Salir de pantalla completa':'Pantalla completa';fs.setAttribute('aria-label',fs.title);document.documentElement.classList.toggle('is-fullscreen',a)}
async function enterFullscreen(){const el=document.documentElement;try{if(el.requestFullscreen){try{await el.requestFullscreen({navigationUI:'hide'})}catch{await el.requestFullscreen()}}else if(el.webkitRequestFullscreen){el.webkitRequestFullscreen()}else throw Error('unsupported')}catch(e){message('Este navegador no permite pantalla completa real. En iPhone/iPad instala Lorens QP en la pantalla de inicio para usarla como app.')}}
async function exitFullscreen(){try{if(document.exitFullscreen)await document.exitFullscreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen()}catch(e){console.warn('No se pudo salir de pantalla completa',e)}}
fs.addEventListener('click',async()=>{if(fsEl())await exitFullscreen();else await enterFullscreen()});
document.addEventListener('fullscreenchange',syncFS);document.addEventListener('webkitfullscreenchange',syncFS);window.addEventListener('resize',()=>document.documentElement.style.setProperty('--app-height',`${window.innerHeight}px`));syncFS();
function slug(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,32)||'senal-ir'}
async function loadIR(){const box=$('irCodes');box.innerHTML='<small>Cargando…</small>';try{const snap=await getDocs(query(collection(db,'qpAir',deviceId,'irCodes'),limit(30)));box.innerHTML='';snap.forEach(d=>{const x=d.data(),row=document.createElement('div');row.className='ir-code';row.innerHTML=`<span>${escapeHtml(x.name||d.id)}</span><small>${escapeHtml(x.protocol||'RAW')} · ${Array.isArray(x.raw)?x.raw.length:0} pulsos</small><button type="button" class="ir-send">Enviar</button>`;row.querySelector('.ir-send').addEventListener('click',async()=>{try{await setDoc(ref('irSend'),{id:crypto.randomUUID(),slot:d.id,createdAt:serverTimestamp()});$('learnStatus').textContent='Señal enviada a la tarjeta.'}catch(e){$('learnStatus').textContent='No se pudo enviar la señal IR.'}});box.append(row)});if(!box.children.length)box.innerHTML='<small>Aún no hay señales guardadas.</small>'}catch{box.innerHTML='<small>No se pudieron leer las señales. Revisa las reglas.</small>'}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('learnIr').addEventListener('click',async()=>{const name=$('irName').value.trim();if(!name){$('learnStatus').textContent='Escribe un nombre para la señal.';return}if(!online()){$('learnStatus').textContent='La tarjeta debe estar disponible.';return}const id=crypto.randomUUID(),slot=slug(name);$('learnIr').disabled=true;$('learnStatus').textContent='Listo: apunta el control a la tarjeta y pulsa el botón durante los próximos 20 segundos.';try{await setDoc(ref('learn'),{id,slot,name,createdMs:Date.now(),createdAt:serverTimestamp()});let tries=0;const timer=setInterval(async()=>{tries++;const snap=await getDocs(collection(db,'qpAir',deviceId,'irCodes'));let found=false;snap.forEach(d=>{if(d.id===slot&&d.data().id===id)found=true});if(found||tries>14){clearInterval(timer);$('learnIr').disabled=false;$('learnStatus').textContent=found?'Señal aprendida y guardada en Firestore.':'No se recibió una señal. Inténtalo de nuevo y acerca el control al receptor.';loadIR()}},1500)}catch(e){$('learnIr').disabled=false;$('learnStatus').textContent='No se pudo iniciar el aprendizaje. Revisa las reglas de Firestore.'}});$('refreshIr').addEventListener('click',loadIR);
connect();loadIR();window.addEventListener('offline',()=>fail('Sin internet'));window.addEventListener('online',render);setInterval(render,5000);
